version: "2"

run:
  timeout: 5m

linters:
  default: all

  disable:
    - testpackage
    - unparam
    - tagliatelle
    - recvcheck
    - paralleltest
    - nlreturn
    - nonamedreturns
    - perfsprint
    - nestif
    - mnd
    - goconst
    - ireturn
    - gocritic
    - gochecknoglobals
    - intrange
    - forcetypeassert
    - funlen
    - gosmopolitan
    - exhaustruct
    - err113
    - exhaustive
    - depguard
    - dupword
    - cyclop
    - errorlint
    - revive
    - gosec
    - gocognit

    - wsl

  settings:
    exhaustruct:
      allow-empty: true
    varnamelen:
      ignore-names:
        - ok

formatters:
  enable:
    - gofmt
    - gofumpt
    - gci
    - golines

  settings:
    gofumpt:
      module-path: github.com/alchemmist/lazy-tmux
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/alchemmist/lazy-tmux
