run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - tenv

    - testpackage
    - unparam
    - tagliatelle
    - recvcheck
    - paralleltest
    - nlreturn
    - nonamedreturns
    - perfsprint
    - nestif
    - mnd
    - goconst
    - ireturn
    - gocritic
    - gochecknoglobals
    - intrange
    - forcetypeassert
    - funlen
    - gosmopolitan
    - exhaustruct
    - err113
    - exhaustive
    - depguard
    - dupword
    - cyclop
    - errorlint
    - revive
    - gosec
    - gocognit
