project_name: lazy-tmux

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: lazy-tmux
    main: ./cmd/lazy-tmux
    binary: lazy-tmux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  use: git
